### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by awhitneye**
@NickTAdams : 
This PR relates to tickets:

<blockquote class="trello-card"><a href="https://trello.com/c/80Rk1CRD/2-1-integrate-airbnb-style-guide-for-linting-requirements-in-eslint-config-file">[1] Integrate AirBnB style guide for linting requirements in eslint config file.</a></blockquote>

The objective was to set up the necessary config files and package.json that I predict will be needed for the development of this module, and to require AirBnB linting style in development.

New files included in the root folders:
.eslintrc
package.json
.babelrc

In addition, there are new files within:
/public, and
/client directories

Please review and tell me what you think!
Thanks,
Andrea

### CODE REVIEW

**Comment by NickTAdams** [comment]
@awhitneye ,
Looks like everything is installing, and the delinter is loading just fine in my VS Code. A couple of things:

- **seed_data.js** : there is a lot of markup from the de-linter. I would suggest cleaning this up so that you are consistent with the AirBnb style that you are using.
- I'm not sure about including the **axios** and **postgres** investigation tickets with this PR, since it is unclear to me on how to evaluate that. If you want to discuss these maybe we can do it over slack, in person, or zoom?

Good job on getting eslint to work! I may hit you up later if I transition to the AirBnb style guide..

Cheers,
Nick

**Comment by awhitneye** [comment]
@NickTAdams Thank you.  Updated seed_data.js and removed references to Trello tickets where applicable.  Mind giving it a second look?

**Comment by NickTAdams** [comment]
@awhitneye 
Nice! I also noticed that you have the example folder uploaded to git. HR asked us to please not upload that. After removing that folder from the git, feel free to merge!
Cheers,
Nick

**Review by NickTAdams — CHANGES_REQUESTED** [review]
@awhitneye please refer to my comment. Just trying out the review functionality.

**Review by NickTAdams — APPROVED** [review]

**Comment by NickTAdams** [comment]
Approved!

**Pull request merged**
