### PR TITLE
Faker

### PR DESCRIPTION
**Pull request by awhitneye**
Hello @melvinest ,
This PR relates to tickets:

<blockquote class="trello-card"><a href="https://trello.com/c/9RUB5VOE/1-2-generate-mock-data-of-several-related-businesses-for-each-of-200-seed-team-welp-businesses">[2] Generate mock data of several related businesses for each of 200 "seed" Team Welp businesses.</a></blockquote>

The objective was to create helper functions to generate fake businesses related to any particular business ID in our shared dataset of 200 businesses, and to use Jest to test these helper functions

New files are largely in the db folders, and include:
fakeData.js
data.test.js

In addition, new scripts and dependencies were added to package.json, to require Jest, and run it as a test script.

Please review and tell me what you think!
Thanks,
Andrea

### CODE REVIEW

**Comment by melvinest** [comment]
Hey Andrea,

Any update on the status of your revision? Have you found a way to remove all the unnecessary files? I'm already going to review nick's pull request so it might be better to ask Nick to review what you have updated once you are done. I think in our round robin nick is the first one to review your code.

Melvin

**Comment by awhitneye** [comment]
@melvinest 

Please see the updates to the request - I have manually deleted node_modules and coverage directories, included a .gitignore file to appropriately remove these files from the repo, and am able to re-download all required modules without them appearing in commits.  
Please let me know if this works on your end as well, and if there's anything else you'd like for me to address.

Thank you!

**Comment by melvinest** [comment]
@awhitneye 
Hey Andrea,
The code looks good to me. I only noticed one minor issue with your gitignore. bundle.js is not included. Currently the file will not be troublesome since you haven't started on your react app yet but it can get really big. One way I saw people handle it is by adding a dist folder inside public and configure webpack so the bundle.js is saved there.

I also noticed that when I downloaded the file I still got the node_modules folder even though it's already included in gitignore. I wonder what's the issue there.

Edit: Once you get this issue sorted out I think you can merge the code to the master.

Melvin

**Comment by awhitneye** [comment]
@melvinest I think you have to completely delete my old code and then re-clone.  That's what worked for me.  Let me know if that works.  
I have included the bundle.js file in the latest iteration.
Let me know how this shakes out - 

Andrea

**Comment by awhitneye** [comment]
Verbally approved by @melvinest

**Pull request merged**
